// <auto-generated />
using System;
using GroceryListManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GroceryListManager.Migrations
{
    [DbContext(typeof(GroceryListManagerContext))]
    [Migration("20191111041406_SeedBooks")]
    partial class SeedBooks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GroceryListManager.Models.GroceryList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Price");

                    b.Property<DateTime?>("PurchasedDate");

                    b.HasKey("Id");

                    b.ToTable("GroceryList");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cereal",
                            Price = "10$",
                            PurchasedDate = new DateTime(2019, 11, 10, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            Name = "Eggs",
                            Price = "6$",
                            PurchasedDate = new DateTime(2019, 11, 10, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            Name = "Apples",
                            Price = "9$",
                            PurchasedDate = new DateTime(2019, 11, 10, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            Name = "Milk",
                            Price = "9$",
                            PurchasedDate = new DateTime(2019, 11, 10, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 5,
                            Name = "Yogurt",
                            Price = "8$",
                            PurchasedDate = new DateTime(2019, 11, 10, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
